removing the prompt assembly and correcting the presentation of the m…
lucaspineda/my-recipe-app pull request #2
Opened 2024-09-25 02:18 UTC by Jefferson-W

criei o estado "optionMealAfter" pq quando mudava a opção mesmo sem gerar receita, ele trocava o texto

2024-09-30 12:46 UTC, lucaspineda approved these changes

2024-09-30 12:50 UTC, lucaspineda requested changes
Na verdade isso é melhor que venha do backend, aí não precisa fazer criar este estado no front end, já que o back vai retornar a mealOption utlizada.

2024-09-30 15:23 UTC, Jefferson-W commented
> Na verdade isso é melhor que venha do backend, aí não precisa fazer criar este estado no front end, já que o back vai retornar a mealOption utlizada.

2024-10-01 02:10 UTC, lucaspineda approved these changes

2024-10-01 02:10 UTC, merged